name: Windows Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Flutter SDK
      shell: pwsh
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.29.1-stable.zip" -OutFile "flutter.zip"
        Expand-Archive -Path flutter.zip -DestinationPath .
    
    - name: Add Flutter to PATH
      shell: pwsh
      run: |
        echo "$env:GITHUB_WORKSPACE\flutter\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Flutter doctor
      run: flutter doctor -v
    
    - name: Enable Windows Desktop
      run: flutter config --enable-windows-desktop
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build Windows
      run: flutter build windows
    
    - name: Archive build
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/windows/x64/runner/Release/
        retention-days: 7

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        Compress-Archive -Path "build/windows/x64/runner/Release/*" -DestinationPath "SimpleViewer-windows.zip"
        $tag = "${{ github.ref_name }}"
        $response = gh release create "$tag" SimpleViewer-windows.zip --generate-notes --title "Release $tag" --latest
        $releaseUrl = "${{ github.server_url }}/${{ github.repository }}/releases/latest"
        echo "RELEASE_URL=$releaseUrl" >> $env:GITHUB_ENV

    - name: Send Discord Notification
      if: startsWith(github.ref, 'refs/tags/') && success()
      shell: pwsh
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        $MESSAGE = @{
          content = "🚀 New Windows build ${{ github.ref_name }} available! $env:RELEASE_URL"
        } | ConvertTo-Json
        
        Invoke-RestMethod -Uri $env:DISCORD_WEBHOOK -Method Post -Body $MESSAGE -ContentType 'application/json'